-- Run from the Database client, yet there is no script to run them automatically
CREATE  TABLE `gandhidb`.`MERCHANT_DETAILS` (
  `MERCHANT_ID` BIGINT NOT NULL ,
  `BUSINESS_NAME` VARCHAR(45) NULL ,
  `EMAIL` VARCHAR(45) NULL ,
  `FIRST_NAME` VARCHAR(45) NULL ,
  `SECOND_NAME` VARCHAR(45) NULL ,
  `PHONE_NUMBER` VARCHAR(45) NULL ,
  `INDUSTRY` VARCHAR(45) NULL ,
  `POSTAL_CODE` VARCHAR(45) NULL ,
  `CITY` VARCHAR(45) NULL ,
  `STATE` VARCHAR(45) NULL ,
  `COUNTRY` VARCHAR(45) NULL ,
  `STORE` VARCHAR(45) NULL ,
  `PRIMARY_WEBSITE` VARCHAR(45) NULL ,
  `SHOPING_CART_OR_POS_SOFTWARE` VARCHAR(45) NULL ,
  PRIMARY KEY (`MERCHANT_ID`) );
